### ISSUE TITLE
Support Typescript

### ISSUE THREAD

**Issue by ricardo-cantu** [i18next/i18next-http-middleware#10]
## 🚀 Feature Proposal

Support typing like i18next-express-middleware did via index.d.ts file

## Motivation

This module is not typed and difficult to use in a typescript project

## Example

Better development experience in a typescript project.

**Comment by adrai** [comment]
https://github.com/i18next/i18next-http-middleware/issues/5
>If you want to provide and maintain them, yes 😉
Just submit a PR.
Personally, I will not be able to provide typescript definitions.
