### ISSUE TITLE
'basic' example does not run

### ISSUE THREAD

**Issue by marisademeglio** [i18next/i18next-http-middleware#13]
## 🐛 Bug Report
'basic' example throws ERR_REQUIRE_ESM

## To Reproduce

Clone this repo
```
cd example/basic
npm i
npm run start
```

## Expected behavior

Example program would start without error and launch an express server on localhost.

## Your Environment

- *runtime version*: node 13.5.0
- *i18next version*: 1.0.1
- *os*: macOS 10.15.4

**Comment by adrai** [comment]
please try with node 12 or 14... 
13 was unstable and had some issues with this

**Comment by marisademeglio** [comment]
Thanks, it runs ok on Node 14
