### ISSUE TITLE
zh-hans zh-hant support

### ISSUE THREAD

**Issue by svengau** [i18next/i18next-http-middleware#16]
The [header language lookup](https://github.com/i18next/i18next-http-middleware/blob/c296a6bec0cfeae705e495ea922197b19ae86a59/lib/languageLookups/header.js#L16), only accepts languages like xx-YY, so zh-Hans and zh-Hant become both zh-HA.

Would it be possible to:
1/ update the regex with (([a-z]{2})-?([A-Z]{2,4})?)\s*;?\s*(q=([0-9.]+))?
OR
2/ have an option to this detector, like `lookupHeaderRegex` to be able to configure it

in both case, I can propose a PR. 

Thanks

**Comment by adrai** [comment]
For sure... try a PR the way you like to.
In the i18next core these are already “special” cases: https://github.com/i18next/i18next/blob/master/src/LanguageUtils.js#L39

**Comment by svengau** [comment]
@adrai Here is a proposal: https://github.com/i18next/i18next-http-middleware/pull/17

**Comment by adrai** [comment]
released in v3.0.1, should be able to detect zh-hans also without setting a custom lookupHeaderRegex
