### ISSUE TITLE
Set cookie depending on other cookie

### ISSUE THREAD

**Issue by borispoehland** [i18next/i18next-http-middleware#18]
## 🚀 Feature Proposal

I don't know if this is possible, but it'd be great if there was a option to only set the language cookie when another cookie is set.

## Motivation

Users may wish to disable all cookies, including the language cookie. As of now, I'm not aware of a mechanism of **conditionally** setting the language cookie 

## Example

Maybe something like:
```
cookieSecure: ...
cookieDependsOn: "hasConsentedToCookiesCookie"
   
```
Then, if `hasConsentedToCookiesCookie` is set, the language cookie gets set, otherwise not.

Again, I don't know if that's possible. I'm looking forward to hearing your feedback!

Best regards

**Comment by adrai** [comment]
It is currently not possible.
Feel free to try a PR.

**Comment by jamuhl** [comment]
adding, removing `cookie` from the options.caches should be enough...(plus removing that cookie on consent remove via userland code)

**Comment by borispoehland** [comment]
@jamuhl sorry, I don't understand quite right, what do you mean?

**Comment by jamuhl** [comment]
the detector options has an option `caches` which enables where to store the current locale -> removing cookie from there does avoid setting that cookie...so optout = removing the cookie from caches and removing the cookie from cookies

**Comment by borispoehland** [comment]
@jamuhl I understand, but for a opt-in solution the code would have to be modified, right?

**Comment by jamuhl** [comment]
opt-in...would be adding cookie to caches and do a `i18next.changeLanguage(i18next.language)` (untested but should work)

**Comment by borispoehland** [comment]
Thank you @jamuhl, it worked!
