### ISSUE TITLE
Difference with i18next-express-middleware

### ISSUE THREAD

**Issue by saveman71** [i18next/i18next-http-middleware#2]
Hello,

We're using `i18next-express-middleware` since a while now. I just saw the deprecation notice in favor to `i18next-http-middleware`, is this just a drop-in replacement?

Do I consider that the latest version of `i18next-express-middleware` is the current `i18next-http-middleware`?

I feel like it's missing a "coming from `i18next-express-middleware`?" section in the README somewhere ;)

**Comment by adrai** [comment]
thx, just added this to the readme:


<<It's based on the deprecated [i18next-express-middleware](https://github.com/i18next/i18next-express-middleware) and can be used as a drop-in replacement.
*It's not bound to a specific http framework anymore.*>>
