### ISSUE TITLE
LanguageDetector lookup function to be async

### ISSUE THREAD

**Issue by Mahan-F** [i18next/i18next-http-middleware#20]
## 🚀 Feature Proposal

Is it possible to have the detector wait for the [lookup](https://github.com/i18next/i18next-http-middleware/blob/master/lib/LanguageDetector.js#L58) function so that operations such as getting the language from a DB can also be used as custom detectors?

I'm not sure if this is already possible and i'm doing something wrong but I couldnt figure out why my custom detector wasnt being used and the next detector in-line was being used (cookie). As soon as I removed the database operation from my detector and simply did a `return 'el'` it was working properly. 

## Motivation

I have created a custom detector which is the first priority detector in the `order` array. This does not work since the function I linked above does not wait for the detector to finish. 

If the maintainers agree with this change, I can submit a PR which makes the lookup function await and have all the current detectors (cookie, session...) Promise based.

**Comment by adrai** [comment]
You can create your own language detector and set async to true: https://www.i18next.com/misc/creating-own-plugins#languagedetector

**Comment by Mahan-F** [comment]
Thanks for the response @adrai. I have already seen that page, my question is can I use two language detectors? Because I still want to use the detectors from this plugin since I am using `cookie` and `header` options. I just need to have my database as the first priority detector and if no value in database exists for the specific user, to use the next options.

**Comment by Mahan-F** [comment]
I believe if this simple change is made, the custom detectors created through this plugin have the option to be async or not. And I believe this will not break anything for other users.

```js
detectionOrder.forEach( async detectorName => {
      if (found || !this.detectors[detectorName]) return

      if ( this.detectors[detectorName].async ) {
          let detections = await this.detectors[detectorName].lookup(req, res, this.options)
      } else {
          let detections = this.detectors[detectorName].lookup(req, res, this.options)
      }

      if (!detections) return
      if (!Array.isArray(detections)) detections = [detections]

      if (this.services.languageUtils.getBestMatchFromCodes) { // new i18next v19.5.0
        found = this.services.languageUtils.getBestMatchFromCodes(detections)
        if (found) req.i18nextLookupName = detectorName
      } else {
        found = detections.length > 0 ? detections[0] : null // a little backward compatibility
      }
    })
```

**Comment by adrai** [comment]
This will not work... 
it needs to be sync or async (with callback signature) but not both...

**Comment by adrai** [comment]
btw: async will not work anyway, because the middleware assumes it's always sync

**Comment by Mahan-F** [comment]
I understand, sorry for the bother. I guess I don't fully understand how the middleware works.
