### ISSUE TITLE
Support for Feathers framework

### ISSUE THREAD

**Issue by sbsujith** [i18next/i18next-http-middleware#27]
Thank you in advance for the rich features.

Do you support Feathers Js framework (https://feathersjs.com/)? 
If so please provide an example.
Cheers...

**Comment by adrai** [comment]
Never heard about feathers...
But if it is middleware compatible, it can be used like in the express example: https://github.com/i18next/i18next-http-middleware/blob/master/example/basic/index.js#L27
I just saw this example, so you may just try: https://github.com/feathersjs/feathers-chat/blob/crow/src/app.js#L29

**Comment by sbsujith** [comment]
Feathers is built on Express. So it should be possible to integrate into middleware. Let me try. Thank you.
