### ISSUE TITLE
Automatic language detection doesn't work with Safari

### ISSUE THREAD

**Issue by CusthomeDev** [i18next/i18next-http-middleware#29]
## Describe the bug

Automatic language detection doesn't work with Safari

## Occurs in i18next-http-middleware version

3.0.5

## Step to reproduce

Use example with safari

##  Reflection

safari only provide full locales ie : 'de-de' and not language like 'de'
so the following code can't work correctly
and found return undefined

```
if (found) {
   if (this.options.ignoreCase) {
      if (detections.map(d => d.toLowerCase()).indexOf(found.toLowerCase()) < 0) found = undefined
      } else {
      if (detections.indexOf(found) < 0) found = undefined
   }
}
```

**Comment by adrai** [comment]
Which example?

**Comment by CusthomeDev** [comment]
basic exemple in 3.0.5

**Comment by jamuhl** [comment]
![image](https://user-images.githubusercontent.com/977772/94539971-34b25200-0246-11eb-9936-b850b4a737e8.png)

why should it not work...navigator language is fully qualified locale if set so.

**Comment by adrai** [comment]
> basic example in 3.0.5

there is no fr in that example

**Comment by adrai** [comment]
Just added fr now... https://github.com/i18next/i18next-http-middleware/commit/df8ae5365a4eea2eda90f903d419bc8c4cddd30f seems to work for me:
![image](https://user-images.githubusercontent.com/1086194/94540531-dafe5780-0246-11eb-972c-d660af892a08.png)

**Comment by CusthomeDev** [comment]
you try with safari ?

**Comment by adrai** [comment]
safari:
![image](https://user-images.githubusercontent.com/1086194/94541378-cff7f700-0247-11eb-9c93-a8dcdac65c0e.png)

**Comment by CusthomeDev** [comment]
you are in i18next-http-middleware 3.0.5 ?

**Comment by adrai** [comment]
> you are in i18next-http-middleware 3.0.5 ?

yes

**Comment by CusthomeDev** [comment]
how it's possible ...

<img width="217" alt="Capture d’écran 2020-09-29 à 11 39 02" src="https://user-images.githubusercontent.com/38779953/94542299-e94d7300-0248-11eb-8f12-44a99c942a38.png">

your script found 'fr' and your detections have only 'fr-fr' so this line `if (detections.indexOf(found) < 0) found = undefined` return undefined

**Comment by adrai** [comment]
which i18next version have you installed?

**Comment by CusthomeDev** [comment]
"i18next": "19.7.0"

**Comment by adrai** [comment]
I just tried on a different machine...
yes, seems the navigator language differs...
just set ignoreCase to true

**Comment by adrai** [comment]
Just released a new version v3.0.6 where ignoreCase option is true by default

**Comment by CusthomeDev** [comment]
Ok thank you for your help

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏

**Comment by dcharbonnier** [comment]
I don't think this issue is solved, if you only send "de-de" and not "de-de, de" ignoreCase solve only a part of the porblem ["de-de"]indexOf("de") => undefined

**Comment by adrai** [comment]
> I don't think this issue is solved, if you only send "de-de" and not "de-de, de" ignoreCase solve only a part of the porblem ["de-de"]indexOf("de") => undefined

It loops through all detections...
I can't reproduce your issue...
Please provide a reproducable example, and if there is still an issue open a new issue.
