### ISSUE TITLE
Automatic language detection doesn't work with Safari

### ISSUE THREAD

**Issue by dcharbonnier** [i18next/i18next-http-middleware#31]
## 🐛 Bug Report

Automatic language detection doesn't work with Safari

## To Reproduce

Run the example/basic with those options :

https://gist.github.com/dcharbonnier/a94f151f382b96fb72f4098e2e8d99f6
```js
supportedLngs: ['en', 'de'],
fallbackLng: 'en',
load: 'all',
```
curl with the headers **safari use** :
```
curl localhost:8080 -H 'Accept-Language: de-de'
Hello World!
```
## Expected behavior

```js
Hallo Welt!
```

## Your Environment

**irrelevant**
- *runtime version*: v15.5.0
- *i18next version*: 6a9b09c
- *os*: Docker alpine node official container

**Comment by adrai** [comment]
This is because of your options.

You have 2 possibilities:
1) remove the `supportedLngs` option
2) add `preload: ['en', 'de']` to the options.

**Comment by dcharbonnier** [comment]
it doesn't look like 2 is removing the issue.
if I remove supportedLngs I will have req.language that can be anything
if I do nonExplicitSupportedLngs=true, req.language will be de-DE.
if I use load all and supportedLngs I expect req.language to be "de" and the translation to be done according to this lang.

![image](https://user-images.githubusercontent.com/6220422/103679334-ffc04480-4f84-11eb-91e0-cb668412bc14.png)

**Comment by adrai** [comment]
for me this works:
![image](https://user-images.githubusercontent.com/1086194/103683397-6f84fe00-4f8a-11eb-91b4-f719a755c090.png)
```
curl localhost:8080 -H 'Accept-Language: de-de'
Hallo Welt!%
```

**Comment by adrai** [comment]
btw: if you use `load: 'languageOnly'`
![image](https://user-images.githubusercontent.com/1086194/103685416-7cefb780-4f8d-11eb-9048-27b75300b660.png)
```
curl localhost:8080 -H 'Accept-Language: de-de'
{
  "req.language": "de-DE",
  "req.i18n.language": "de-DE",
  "req.i18n.languages": [
    "de",
    "en"
  ],
  "req.i18n.languages[0]": "de",
  "req.t(\"home.title\")": "Hallo Welt!"
}%
```

![image](https://user-images.githubusercontent.com/1086194/103685466-9133b480-4f8d-11eb-8c18-16bcdfbcec3a.png)
