### ISSUE TITLE
Express get started code is flawed: init call is async

### ISSUE THREAD

**Issue by StephaneBischoff** [i18next/i18next-http-middleware#45]
### Do you have a documentation issue?
The Get Started section for Express seems flawed. (https://github.com/i18next/i18next-http-middleware#wire-up-i18next-to-request-object)
It was not working for me until I realized that `init` returns a `Promise`.
```
i18next.use(middleware.LanguageDetector).init({
  preload: ['en', 'de', 'it'],
  ...otherOptions
})
```
I changed to this for it to work. 
```
await i18next.use(middleware.LanguageDetector).init({
  preload: ['en', 'de', 'it'],
  ...otherOptions
})
```
Maybe its my express setup, but just wanted to raise the issue.

## Documentation issue

See above

## Motivation

See above

**Comment by adrai** [comment]
Yes init can return a promise... but the question is: why do you need to wait for it?

**Comment by StephaneBischoff** [comment]
Closing it. Removed the await and everything still working. I had a undefined exception before which I thought was maybe causes be the code executing pass the Promise...
