### ISSUE TITLE
Add ability to load a single source bundle, or document if it already is possible

### ISSUE THREAD

**Issue by dietergeerts** [i18next/i18next-http-middleware#46]
## 🚀 Feature Proposal

Having a `getResourceHandler` to load a single resource bundle, similar to `getResourcesHandler`.

## Motivation

I was under the impression that adding this middleware would automatically add these endpoints or handle requests for a single resource bundle, but it appears this is not the case. The current use-case we have is to serve resource bundles and save missing keys during testing and Storybook usage, meaning that we don't need actual language negotiation for our request, just the ability to get the bundles. In order to satisfy this use-case, having a handler to serve a single resource bundle will help. A current workaround is to install the backend extender to do a call for multiple resource bundles, but I would like to not do this.

## Example

This is difficult. I'm having some custom code to "glue" the middlewares/handlers provided by this package to the Karma test runner and Webpack-dev-server, in order to work with our translation files during development with unit-tests and Storybook. If code is required, or more details are needed, let me know, and I'll provide them. Maybe I'm missing something, so there could be a better workaround possible. With debugging and investigating the code, I couldn't find any.

**Comment by adrai** [comment]
Do you use a query string parameter? like here: https://github.com/i18next/i18next-http-middleware/commit/491720691b836822f1f6099b61d1611eb4c64f52

**Comment by dietergeerts** [comment]
> Do you use a query string parameter? like here: [4917206](https://github.com/i18next/i18next-http-middleware/commit/491720691b836822f1f6099b61d1611eb4c64f52)

That's a possibility, but I will still get the bundles grouped by language and namespace, which isn't what the http-backend is expecting. I added a custom middleware which wraps this one to get several bundles, by adding the query params, and then extract the one bundle needed, but it would be nice if this was included by default.

**Comment by adrai** [comment]
Sorry, but then I do not understand what you actually want to achieve.

Can you maybe create a concrete example? An example repo or similar?
