### ISSUE TITLE
i18next-http-middleware in Hapi js 

### ISSUE THREAD

**Issue by emanuelet** [i18next/i18next-http-middleware#48]
## 🚀 Feature Proposal

Would it be possible an `.hapiPlugin` function to support HapiJs? 

## Motivation

The "official" package https://github.com/kenkouot/hapi-i18next is not been maintained anymore. Also I will like more the agnostic middleware approach.

## Example

On our backend application we used this code to get it to work: 
```javascript
server.ext('onPreHandler', (request, h) => {
      let resp = request.Response || request.response || h.response()
      i18nextMiddleware(request, resp, () => {
        return true
      })
      return h.continue
    })
```

**Comment by adrai** [comment]
Would you like to send a Pull Request to address this? Remember to add tests.

**Comment by emanuelet** [comment]
Wokring on the PR
