### ISSUE TITLE
Custom language detector not working

### ISSUE THREAD

**Issue by azuken** [i18next/i18next-http-middleware#51]
## 🐛 Bug Report

When trying to make your own language detection, like explained in README, it does not work (lookup function is not running). i18n is initializing with fallback language.

## To Reproduce

```js
import i18next, { TFunction } from 'i18next';
import middleware from 'i18next-http-middleware';
import Backend from 'i18next-node-fs-backend';

export const customDetector: middleware.LanguageDetectorInterface = {
  name: 'customDetector',
  lookup: (req: {
    body: {
      commonEventObject: any;
      calendar: any;
      authorizationEventObject: any;
    };
  }) => {
    logger.debug('Custom detector lookup');
    logger.debug('userLocale', req.body.commonEventObject.userLocale);

    switch (req.body.commonEventObject.userLocale) {
      case 'en':
        return 'en-US';
      case 'fr':
        return 'fr-FR';
      default:
        return 'en-US';
    }
  }
};

const languageDetector = new middleware.LanguageDetector();
languageDetector.addDetector(customDetector);

export const initI18n = (): Promise<TFunction> =>
  i18next
    .use(Backend)
    .use(languageDetector)
    .init({
      backend: {
        loadPath: './public/locales/{{lng}}/{{ns}}.json'
      },
      detection: {
        order: ['customDetector']
      },
      fallbackLng: 'fr-FR',
      supportedLngs: ['fr-FR', 'en-US'],
      preload: ['fr-FR', 'en-US']
    });

```

## Expected behavior

Lookup function must return right locale.
I've tried se same code with `i18next-browser-languageDetector` library, lookup is working fine (excepting `req` parameter which is not present).

## Your Environment

- *runtime version*: node v17.5
- *i18next version*: 21.6.14 (i18next-http-middleware 3.2.0)
- *os*: Mac (and Docker Linux image on AWS instance)

**Comment by adrai** [comment]
Currently afk... could check in a couple of hours... in the meantime you could create a reproducible repo? And/or maybe try to debug the i18next-http-middleware code?

**Comment by adrai** [comment]
fyi: just tried it in this example: https://github.com/i18next/i18next-http-middleware/commit/40fda3719079f3f2c3d17d0fb3bc7f061def81d2 seems to work as expected.

Please provide a reproducible example.

**Comment by azuken** [comment]
Thank you for your response, with your example I found what was not working ; I didn't add express usage of middleware. I didn't see this line in README, sorry for bothering you !

```js
app.use(i18nextMiddleware.handle(i18next))
```

**Comment by azuken** [comment]
After some tests, middleware is running when I make API calls (lookup function is ok), but `fallbackLng` is still the only entry used by i18next.

Even I force lookup function to return 'en-US', it's still returning 'fr-FR', or i18n key if I delete `fallbackLng`.

**Comment by adrai** [comment]
Please provide a complete reproducible example.

**Comment by azuken** [comment]
[i18n-issue.zip](https://github.com/i18next/i18next-http-middleware/files/8462948/i18n-issue.zip)

Here !

**Comment by adrai** [comment]
You are using the wrong t function!

In your root.js file, instead of:
`res.json({test: t('app.test')});`

use t from req:
`res.json({test: req.t('app.test')});`


btw: i18next-node-fs-backend is deprecated, use [i18next-fs-backend](https://github.com/i18next/i18next-fs-backend) instead, and set `initImmediate: false` in your options, this way you do not need to wait for an extra promise...
<img width="516" alt="image" src="https://user-images.githubusercontent.com/1086194/162715551-41827161-e9bb-4532-8f66-e25879729a3e.png">

**Comment by azuken** [comment]
Thank you, it's working from `req.t`, I thought middleware was updating global `t` function.

And thank you for the deprecated package advice !

Just in case, is there a generic way to get this `req.t` function, from middleware for example, instead of passing it as parameter for each function using it ?

**Comment by adrai** [comment]
No, the global t function is not update and should never be updated, because of concurrency.
Think of having 2 concurrent requests, one detected in en-US and the other fr-FR... which language should be set in the global instance? That's why you always need to access the t function in the request.

**Comment by azuken** [comment]
Indeed! Thank you for your time.

**Comment by azuken** [comment]
Sorry to bother again, it seems that `body` parameter in `req`object is not parsed in language detector. I've got undefined values (with query it's working fine), and I can get `body` inside `Router` (in `asyncHandler`).

I've search in the documentation, and found this : https://github.com/i18next/i18next-http-middleware#add-routes but seems not related ?

**Comment by adrai** [comment]
This is probably because of the middleware order...

Just move `app.use(express.json());` before `app.use(i18nextMiddleware.handle(i18next));`

```
app.use(express.json());
app.use(i18nextMiddleware.handle(i18next));
```

from the express docs: https://expressjs.com/en/guide/writing-middleware.html

<img width="900" alt="image" src="https://user-images.githubusercontent.com/1086194/162752986-7705f968-7bbc-496e-b3bb-52da8a1a5d88.png">

**Comment by azuken** [comment]
That was it! Thank you again 😊
