### ISSUE TITLE
Undocumented options for most methods

### ISSUE THREAD

**Issue by lukaromih** [i18next/i18next-http-middleware#57]
## Documentation issue

Most middlewares/plugins in this module have undocumented options and are also not part of any example. Would it be possible to document all available options for those (e.g. for handle method) in the sense that [Detector Options](https://github.com/i18next/i18next-http-middleware#detector-options) are documented.

## Motivation

I've read some articles regarding the use of i18next and different parts of its ecosystem after I've already integrated it successfully into my project. I've rolled my own language switch functionality, but multiple articles mentioned a relatively simple switch without any extra endpoints, simply using a lng query param on the current page. I didn't like the idea of those aditional query params in URL. One of the articles mentioned the `removeLngFromUrl` option however. I've searched for it throughout this module's readme and its examples. Only after a quick glance at source code did it show up.
It would really help to know what other options are available on all the offered middlewares/plugins and what they do.
Apart from that, hats of for a very well maintained and documented ecosystem.

**Comment by adrai** [comment]
The `removeLngFromUrl` option was originally introduced in i18next-express-middleware (I completely missed that option).
I've found also 2 other options... and added a minimal info in the readme
