### ISSUE TITLE
Missing Oak (Deno) support

### ISSUE THREAD

**Issue by Superjd10** [i18next/i18next-http-middleware#59]
## 🐛 Bug Report

`[uncaught application error]: TypeError - url.indexOf is not a function` when trying to use with Deno, for handle c.request / ctx.request.

## To Reproduce

When trying to use i18next-http-middleware with Oak (Deno) with the following code (adaption from the 'abc' implementation):

```js
const handlei18next = i18nextMiddleware.handle(i18next);

app.use((c, next) => {
    handlei18next(c.request, c.response, () => {})
    return next()
})
```

I get the following error:

![image](https://github.com/i18next/i18next-http-middleware/assets/1649155/2a6ddd12-30c3-4b93-939e-b52a9b70e777)

When I changed the `c.request` to only `c` or `c.request.url` it kind of works, but I get the following errors:
```
no possibility found to get query
httpFunctions.js:40
no possibility found to get url // This one dissapears when using c.request.url
httpFunctions.js:11
no possibility found to get headers
```

## Expected behavior

Correct handling of query / search params in handle. I cloned the repo and did a few tests and was able to "fix" the issue adding this to line 38 (checking searchParams inside the url object), also comitted to my fork (I thought it wouldn't be worth adding a pull request for a literal 1 line 😄):
`if (req.url.searchParams) return req.url.searchParams`

## Your Environment

- *runtime version*: Deno 1.34.1 (release, x86_64-pc-windows-msvc)
- *i18next version*: [22.5.1](https://deno.land/x/i18next@v22.5.1)
- *os*: Windows 10 21H2 - 19044.2965

**Comment by adrai** [comment]
try v3.3.2

**Comment by Superjd10** [comment]
Great, thanks!
