### ISSUE TITLE
existingCookie.filter is not a function

### ISSUE THREAD

**Issue by calvinkei** [i18next/i18next-http-middleware#6]
using next-i18next@beta and run `yarn now-build`, causing error `existingCookie.filter is not a function`

the issue is on `cookie.js` line 107, where existingCookie is supposed to be an array, but turns out to be an object instead

**Comment by adrai** [comment]
Will try to check for this, but can you please provide also a reproducable example?

**Comment by adrai** [comment]
Should be better with v1.2.1
Nevertheless, a reproducable example would be nice.

**Comment by adrai** [comment]
this is strage...
just released a new version...
I think the root cause is something different... the response object looks really strange...
Now I get an other error: `TypeError: res.writeHead is not a function`

but not coming from this module

**Comment by adrai** [comment]
https://github.com/zeit/next.js/issues/8953
