### ISSUE TITLE
Add a new configuration item to set the prefix of local variables

### ISSUE THREAD

**Issue by hungtcs** [i18next/i18next-http-middleware#60]
## 🚀 Feature Proposal

Add a new configuration item to allow customizing local variables prefixes.

## Motivation

For consistency and to avoid overwriting, it is necessary to add a prefix.

## Example

```js
middleware.handle(i18next, {
  localsPrefix: '$',
  ignoreRoutes: ['/foo'], // or function(req, res, options, i18next) { /* return true to ignore */ }
  removeLngFromUrl: false // removes the language from the url when language detected in path
})
```

**Comment by adrai** [comment]
Don't know exactly what you mean...
But feel free to provide a PR so maybe I understand what you want to achieve.

**Comment by hungtcs** [comment]
Sorry, I misunderstood the meaning of the code, what I said was not actually needed, please forgive my recklessness.
