### ISSUE TITLE
What is the detection behaviour for the various different language detection methods?

### ISSUE THREAD

**Issue by grug** [i18next/i18next-http-middleware#66]
Hey there,

I'm more than happy to be told to go read the code and work it out from there, but thought I'd give this question a go:

What is the detection behaviour for the language detection mechanism? I know you can specify either a querystring parameter to check, or path etc... but beyond that for a given page load, what behaviour is there? Is that preference saved anywhere internally and that language is used until a further language change is detected? Or is it something else? I can't see anything in the documentation that answers my question - I'm happy to submit a PR to update it once I understand it myself.

Thanks!

**Comment by adrai** [comment]
This is the default order: https://github.com/i18next/i18next-http-middleware?tab=readme-ov-file#detector-options (code: https://github.com/i18next/i18next-http-middleware/blob/master/lib/LanguageDetector.js#L11)

1. querystring
2. cookie
3. header

but you can define your own order...

**Comment by grug** [comment]
@adrai that is an incredibly fast response time! Thank you very much! When you say that this is the default order and you can define your own order, do you mean that this is the order for every page load? 

Would you be open to me opening a PR talking about the language detection behaviour, or is it deemed unnecessary?

**Comment by adrai** [comment]
it is the order for every route that uses the i18next-http-middleware

**Comment by grug** [comment]
Amazing - thanks. Would you be open to a PR updating the documentation to be clear about this?

**Comment by adrai** [comment]
feel free

**Comment by grug** [comment]
Amazing - I'll put something together.
