### ISSUE TITLE
Add the ability to configure the SameSite cookie option

### ISSUE THREAD

**Issue by martpie** [i18next/i18next-http-middleware#7]
## 🚀 Feature Proposal

On the latest Firefox releases, the following warning is issues (using via `next-i18next`).

![Screen Shot 2020-05-22 at 17 03 31](https://user-images.githubusercontent.com/1311607/82681676-6723c100-9c4e-11ea-944a-af459c595fd6.png)

From what I see, this option is not configurable (https://github.com/i18next/i18next-http-middleware/blob/5a2ee9a8188ce5d108ce3ee158054cf5ecb47d45/lib/languageLookups/cookie.js#L78-L83)

Is this something that could be added? https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite

## Motivation

Prevent FF from breaking our website in a future release.

## Example

```
{
  cookieSameSite: 'strict'
}
```

in the config.

**Comment by martpie** [comment]
I think this should not be too hard to implement, maybe I can submit a PR for that :)

**Comment by adrai** [comment]
PR are always welcome ;-)

**Comment by adrai** [comment]
btw: serializeCookie is already prepared for this: https://github.com/i18next/i18next-http-middleware/blob/master/lib/languageLookups/cookie.js#L34

**Comment by adrai** [comment]
adding: `if (options.cookieSameSite) cookieOptions.sameSite = options.cookieSameSite` here should do the trick: https://github.com/i18next/i18next-http-middleware/blob/master/lib/languageLookups/cookie.js#L85

and maybe an addition in the readme

**Comment by martpie** [comment]
Mmmh I don't think so, because `options.cookieSameSite` will be undefined, therefore won't be added to the cookie options in `serializeCookie`, unless I am missing something 🤔
